project:
  type: website
  output-dir: docs

website:
  title: "Katie Knox - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: weekly-notes/
        text: Weekly Notes
      - href: weekly-notes/week-010notes.qmd
        text: "Week 1 Notes"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
