{
  "hash": "bc0bab9c52d4d12fbb69957fe0d36553",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Katie Knox\"\ndate: \"10-2-2025\"\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load spatial data\npa_counties <- st_read(\"data/Pennsylvania_County_Boundaries.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `C:\\Users\\knoxk\\OneDrive\\Documents\\musa-5080\\portfolio-setup-kkxix\\labs\\lab2\\data\\Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- st_read(\"data/hospitals.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `C:\\Users\\knoxk\\OneDrive\\Documents\\musa-5080\\portfolio-setup-kkxix\\labs\\lab2\\data\\hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncensus_tracts <- tracts(state = \"PA\", cb = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |                                                                      |   1%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |=====                                                                 |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |=======                                                               |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |============                                                          |  18%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |==============                                                        |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |================                                                      |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |=======================                                               |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |===========================                                           |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |===============================                                       |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |=================================                                     |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |===================================                                   |  51%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |======================================                                |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |========================================                              |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |==============================================                        |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |================================================                      |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |===================================================                   |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |=========================================================             |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |===========================================================           |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |====================================================================  |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\ncensus_tracts <- st_transform(census_tracts, st_crs(pa_counties))\nhospitals <- st_transform(hospitals, st_crs(pa_counties))\n\n# Check that all data loaded correctly\nglimpse(pa_counties)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 67\nColumns: 20\n$ OBJECTID   <int> 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347,…\n$ MSLINK     <int> 46, 8, 9, 58, 59, 60, 62, 63, 42, 43, 44, 47, 48, 49, 50, 5…\n$ COUNTY_NAM <chr> \"MONTGOMERY\", \"BRADFORD\", \"BUCKS\", \"TIOGA\", \"UNION\", \"VENAN…\n$ COUNTY_NUM <chr> \"46\", \"08\", \"09\", \"58\", \"59\", \"60\", \"62\", \"63\", \"42\", \"43\",…\n$ FIPS_COUNT <chr> \"091\", \"015\", \"017\", \"117\", \"119\", \"121\", \"125\", \"127\", \"08…\n$ COUNTY_ARE <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ COUNTY_PER <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ NUMERIC_LA <int> 5, 2, 5, 2, 2, 3, 1, 2, 1, 3, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1,…\n$ COUNTY_N_1 <int> 46, 8, 9, 58, 59, 60, 62, 63, 42, 43, 44, 47, 48, 49, 50, 5…\n$ AREA_SQ_MI <dbl> 487.4271, 1161.3379, 622.0836, 1137.2480, 319.1893, 683.367…\n$ SOUND      <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ SPREAD_SHE <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ IMAGE_NAME <chr> \"poll.bmp\", \"poll.bmp\", \"poll.bmp\", \"poll.bmp\", \"poll.bmp\",…\n$ NOTE_FILE  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ VIDEO      <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ DISTRICT_N <chr> \"06\", \"03\", \"06\", \"03\", \"03\", \"01\", \"12\", \"04\", \"02\", \"01\",…\n$ PA_CTY_COD <chr> \"46\", \"08\", \"09\", \"59\", \"60\", \"61\", \"63\", \"64\", \"42\", \"43\",…\n$ MAINT_CTY_ <chr> \"4\", \"9\", \"1\", \"7\", \"8\", \"5\", \"4\", \"6\", \"5\", \"4\", \"7\", \"3\",…\n$ DISTRICT_O <chr> \"6-4\", \"3-9\", \"6-1\", \"3-7\", \"3-8\", \"1-5\", \"12-4\", \"4-6\", \"2…\n$ geometry   <MULTIPOLYGON [m]> MULTIPOLYGON (((-8398884 48..., MULTIPOLYGON (…\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(census_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,445\nColumns: 14\n$ STATEFP    <chr> \"42\", \"42\", \"42\", \"42\", \"42\", \"42\", \"42\", \"42\", \"42\", \"42\",…\n$ COUNTYFP   <chr> \"001\", \"013\", \"013\", \"013\", \"013\", \"011\", \"011\", \"011\", \"01…\n$ TRACTCE    <chr> \"031101\", \"100400\", \"100500\", \"100800\", \"101900\", \"011200\",…\n$ GEOIDFQ    <chr> \"1400000US42001031101\", \"1400000US42013100400\", \"1400000US4…\n$ GEOID      <chr> \"42001031101\", \"42013100400\", \"42013100500\", \"42013100800\",…\n$ NAME       <chr> \"311.01\", \"1004\", \"1005\", \"1008\", \"1019\", \"112\", \"2\", \"115\"…\n$ NAMELSAD   <chr> \"Census Tract 311.01\", \"Census Tract 1004\", \"Census Tract 1…\n$ STUSPS     <chr> \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\",…\n$ NAMELSADCO <chr> \"Adams County\", \"Blair County\", \"Blair County\", \"Blair Coun…\n$ STATE_NAME <chr> \"Pennsylvania\", \"Pennsylvania\", \"Pennsylvania\", \"Pennsylvan…\n$ LSAD       <chr> \"CT\", \"CT\", \"CT\", \"CT\", \"CT\", \"CT\", \"CT\", \"CT\", \"CT\", \"CT\",…\n$ ALAND      <dbl> 3043185, 993724, 1130204, 996553, 573726, 1539365, 1949529,…\n$ AWATER     <dbl> 0, 0, 0, 0, 0, 9308, 159015, 12469, 0, 0, 0, 1271, 6352, 74…\n$ geometry   <MULTIPOLYGON [m]> MULTIPOLYGON (((-8575060 48..., MULTIPOLYGON (…\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(hospitals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 223\nColumns: 12\n$ CHIEF_EXEC <chr> \"Peter J Adamo\", \"Autumn DeShields\", \"Shawn Parekh\", \"DIANE…\n$ CHIEF_EX_1 <chr> \"President\", \"Chief Executive Officer\", \"Chief Executive Of…\n$ FACILITY_U <chr> \"https://www.phhealthcare.org\", \"https://www.malvernbh.com\"…\n$ LONGITUDE  <dbl> -79.91131, -75.17005, -75.20963, -80.27907, -79.02513, -75.…\n$ COUNTY     <chr> \"Washington\", \"Philadelphia\", \"Philadelphia\", \"Washington\",…\n$ FACILITY_N <chr> \"Penn Highlands Mon Valley\", \"MALVERN BEHAVIORAL HEALTH\", \"…\n$ STREET     <chr> \"1163 Country Club Road\", \"1930 South Broad Street Unit 4\",…\n$ CITY_OR_BO <chr> \"Monongahela\", \"Philadelphia\", \"Philadelphia\", \"WASHINGTON\"…\n$ LATITUDE   <dbl> 40.18193, 39.92619, 40.02869, 40.15655, 39.80913, 40.24273,…\n$ TELEPHONE_ <chr> \"724-258-1000\", \"610-480-8919\", \"215-483-9900\", \"7248840710…\n$ ZIP_CODE   <chr> \"15063\", \"19145\", \"19128\", \"15301\", \"15552\", \"19464\", \"1776…\n$ geometry   <POINT [m]> POINT (-8895686 4892415), POINT (-8367892 4855223), P…\n```\n\n\n:::\n\n```{.r .cell-code}\n# With ggplot2\np1 <- ggplot(pa_counties) +\n  geom_sf() +\n  theme_void()\n\np2 <- ggplot(census_tracts) +\n  geom_sf() +\n  theme_void()\n\np3 <- ggplot(hospitals) +\n  geom_sf() +\n  theme_void()\n\np1 | p2 | p3\n```\n\n::: {.cell-output-display}\n![](assignment2_kk_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n**Questions to answer:**\n\n- How many hospitals are in your dataset?\n  - 223\n- How many census tracts?\n  - 3445\n- What coordinate reference system is each dataset in?\n  - I transformed hospitals and census tracts to PA counties CRS, which is WGS84. Before that, hospitals were also in WGS84, but census tracts were in NAD83. \n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\npa_tracts_data <- get_acs(\n  geography = \"tract\",\n  variables = c(\n    median_income = \"B19013_001\",\n    total_pop = \"B01003_001\",\n    over_65 = \"B01001_020\"  # Population 65 years and over\n  ),\n  state = \"PA\",\n  year = 2023,\n  output = \"wide\"\n)\n\n# Join to tract boundaries\ncensus_tracts <- census_tracts %>%\n  left_join(pa_tracts_data, by= \"GEOID\")\n\nsummary(census_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   STATEFP            COUNTYFP           TRACTCE            GEOIDFQ         \n Length:3445        Length:3445        Length:3445        Length:3445       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    GEOID              NAME.x            NAMELSAD            STUSPS         \n Length:3445        Length:3445        Length:3445        Length:3445       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  NAMELSADCO         STATE_NAME            LSAD               ALAND          \n Length:3445        Length:3445        Length:3445        Min.   :7.224e+04  \n Class :character   Class :character   Class :character   1st Qu.:1.320e+06  \n Mode  :character   Mode  :character   Mode  :character   Median :4.183e+06  \n                                                          Mean   :3.364e+07  \n                                                          3rd Qu.:2.858e+07  \n                                                          Max.   :1.024e+09  \n                                                                             \n     AWATER            NAME.y          median_incomeE   median_incomeM  \n Min.   :       0   Length:3445        Min.   : 13307   Min.   :   472  \n 1st Qu.:       0   Class :character   1st Qu.: 57864   1st Qu.:  9324  \n Median :   13905   Mode  :character   Median : 72944   Median : 13780  \n Mean   :  433440                      Mean   : 80731   Mean   : 16219  \n 3rd Qu.:  240806                      3rd Qu.: 96691   3rd Qu.: 20141  \n Max.   :29792870                      Max.   :250001   Max.   :208341  \n                                       NA's   :65       NA's   :73      \n   total_popE      total_popM        over_65E         over_65M     \n Min.   :    0   Min.   :   3.0   Min.   :  0.00   Min.   :  2.00  \n 1st Qu.: 2616   1st Qu.: 248.0   1st Qu.: 19.00   1st Qu.: 19.00  \n Median : 3640   Median : 375.0   Median : 39.00   Median : 31.00  \n Mean   : 3770   Mean   : 402.7   Mean   : 47.59   Mean   : 39.76  \n 3rd Qu.: 4810   3rd Qu.: 527.0   3rd Qu.: 66.00   3rd Qu.: 51.00  \n Max.   :10406   Max.   :2091.0   Max.   :324.00   Max.   :342.00  \n                                                                   \n          geometry   \n MULTIPOLYGON :3445  \n epsg:3857    :   0  \n +proj=merc...:   0  \n                     \n                     \n                     \n                     \n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n\n- What year of ACS data are you using?\n  - 2019-2023 5-year ACS data\n- How many tracts have missing income data?\n  - 65\n- What is the median income across all PA census tracts?\n  - $72,944\n\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\nvulnerable_tracts <- census_tracts %>%\n  filter(median_incomeE < 42398 | (over_65E/total_popE) > .017)\n```\n:::\n\n\n**Questions to answer:**\n\n- What income threshold did you choose and why?\n    - I looked at the [2023 poverty guidelines](https://www.pakeys.org/2023-annual-federal-poverty-guidelines/), the average household size in PA in 2023, which was 2.4, and then looked into eligibility for various programs, which is anywhere from 133% FPIG to 215%. I am going with vulnerable household is 215% or less of the 2-person household FPIG, or $42,398.\n- What elderly population threshold did you choose and why?\n    - In order to control for overall population size, instead of looking at the raw number of elderly, I looked at the over 65 as percent of total population. I defined vulnerable as any tract in the 75th percentile of elderly percent of tract population (1.7% or above).\n- How many tracts meet your vulnerability criteria?\n    - 1,145\n- What percentage of PA census tracts are considered vulnerable by your definition?\n    - 33.2% -- about a third. \n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n#convert to Albers\nvulnerable_tracts <- st_transform(vulnerable_tracts, crs = 5070)\nhospitals <- st_transform(hospitals, crs = 5070)\n\n# Calculate distance from each tract centroid to nearest hospital\ntract_centroids <- st_centroid(vulnerable_tracts)\nnearest_hospital <- st_nearest_feature(tract_centroids, hospitals)\n\nvulnerable_tracts <- vulnerable_tracts %>%\n  mutate(nearest_hospital_geom = hospitals$geometry[nearest_hospital])\n\nvulnerable_tracts <- vulnerable_tracts %>%\n  mutate(distance_to_nearst_hospital = set_units(st_distance(tract_centroids, vulnerable_tracts$nearest_hospital_geom, by_element = TRUE), \"mi\"))\n\nsummary(vulnerable_tracts$distance_to_nearst_hospital) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n 0.02107  1.21850  2.75761  4.37494  6.02931 29.75156 \n```\n\n\n:::\n:::\n\n\n**Requirements:**\n\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\nI chose Albers Conical Equal Area, NAD 83 projection based on [this PA document from 2011's](https://elibrary.dcnr.pa.gov/PDFProvider.ashx?action=PDFStream&docID=1743537&chksum=&revision=0&docName=ndards&nativeExt=pdf&PromptToSave=False&Size=152488&ViewerMode=2&overlay=0) recommendation. \n\n**Questions to answer:**\n\n- What is the average distance to the nearest hospital for vulnerable tracts?\n    - 4.4 miles\n- What is the maximum distance?\n    - 29.8 miles\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n    - 33\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\n\nvulnerable_tracts <- vulnerable_tracts %>%\n  mutate(underserved = ifelse(as.numeric(distance_to_nearst_hospital) > 15,\"Underserved\",\"\"))\n\nvulnerable_tracts %>%\n  group_by(underserved)%>%\n  summarise(n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 2 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 1272296 ymin: 1971050 xmax: 1776268 ymax: 2294525\nProjected CRS: NAD83 / Conus Albers\n# A tibble: 2 × 3\n  underserved   `n()`                                                   geometry\n  <chr>         <int>                                         <MULTIPOLYGON [m]>\n1 \"\"             1112 (((1324165 2015512, 1324049 2015276, 1323967 2015195, 132…\n2 \"Underserved\"    33 (((1391776 2000059, 1392091 2000026, 1392335 1999901, 139…\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n\n- How many tracts are under-served?\n    - 33\n- What percentage of vulnerable tracts are under-served?\n    - 3%\n- Does this surprise you? Why or why not?\n    - Unfortunately, this does not surprise me, given how rural certain areas of Pennsylvania are and knowing how rural healthcare is a persistent issue in the US in general. However, it would surprise me if some of these tracts are in urban areas. \n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\npa_counties <- pa_counties %>% st_transform(st_crs(vulnerable_tracts))\n\nvulnerable_per_county <- vulnerable_tracts %>%\n  st_join(pa_counties) %>%\n  st_drop_geometry()\n\n# Aggregate statistics by county\nvulnerable_per_county_stats <- vulnerable_per_county %>%\n  group_by(COUNTY_NAM) %>%\n  summarise(\n    num_vulnerable_tracts = n(),\n    num_underserved_tracts = sum(underserved == \"Underserved\"),\n    percent_underserved = sum(underserved == \"Underserved\")/n(),\n    avg_distance_to_nearst_hospital = mean(distance_to_nearst_hospital),\n    total_pop = sum(total_popE),\n    total_underserved_pop = sum(ifelse(underserved == \"Underserved\", total_popE, 0))\n  )\n```\n:::\n\n\n**Required county-level statistics:**\n\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\n    - Cameron\n    - Juniata\n    - Potter\n    - Snyder\n    - Sullivan\n- Which counties have the most vulnerable people living far from hospitals?\n    - Clearfield\n    - Chester\n    - Juniata\n    - Snyder\n    - Pike\n- Are there any patterns in where underserved counties are located?\n    - There are a lot of quite rural underserved counties, like Sullivan, Juniata, and Clearfield, but there are also suburban counties of major PA cities like Chester County outside of Philadelphia and Cumberland County outside Harrisburg. \n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\nvulnerable_per_county_stats %>% \n  arrange(desc(total_underserved_pop)) %>%\n  slice_head(n = 10) %>%\n  select(\n    c(\"COUNTY_NAM\", \"total_underserved_pop\", \"percent_underserved\", \"avg_distance_to_nearst_hospital\")\n  ) %>%\n  mutate(\n    avg_distance_to_nearst_hospital = as.numeric(avg_distance_to_nearst_hospital),\n    percent_underserved = paste0(round(percent_underserved*100, 2), \"%\")\n  )%>%\n  kable(\n    col.names = c(\"County\", \"Total Underserved Population\", \"Percent of Vulnerable Tracts that are Underserved\", \"Average Distance of to Nearest Hospital\"),\n    digit = 1,\n    format.args = list(big.mark = \",\"),\n    align = \"l\",\n    caption = \"10 Counties in PA with the Highest Absolute Population more than 15 miles from Nearest Hospital\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: 10 Counties in PA with the Highest Absolute Population more than 15 miles from Nearest Hospital\n\n|County     |Total Underserved Population |Percent of Vulnerable Tracts that are Underserved |Average Distance of to Nearest Hospital |\n|:----------|:----------------------------|:-------------------------------------------------|:---------------------------------------|\n|CLEARFIELD |17,027                       |28.57%                                            |12.4                                    |\n|CHESTER    |15,467                       |7.5%                                              |6.1                                     |\n|JUNIATA    |13,955                       |50%                                               |15.4                                    |\n|SNYDER     |12,073                       |50%                                               |15.1                                    |\n|PIKE       |10,292                       |35.29%                                            |15.4                                    |\n|DAUPHIN    |8,815                        |8.33%                                             |5.3                                     |\n|SCHUYLKILL |8,815                        |7.41%                                             |7.0                                     |\n|PERRY      |8,761                        |22.22%                                            |12.3                                    |\n|LANCASTER  |8,055                        |5.71%                                             |5.7                                     |\n|CENTRE     |6,843                        |5.88%                                             |6.2                                     |\n\n\n:::\n:::\n\n\n**Requirements:**\n\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\nvulnerable_per_county_stats <- vulnerable_per_county_stats %>%\n  left_join(pa_counties, by=\"COUNTY_NAM\")\n\nvulnerable_per_county_stats <- vulnerable_per_county_stats %>%\n  st_as_sf() %>% \n  st_transform(st_crs(census_tracts)) %>%\n  mutate(percent_underserved = percent_underserved*100\n  )\n\nhospitals <- hospitals %>%\n  mutate(type = \"Hospital\")\n\nggplot(vulnerable_per_county_stats) +\n  geom_sf(aes(fill = percent_underserved)) +\n  scale_fill_gradient(\n    low = \"#C3CDFE\",   \n    high = \"#485EFE\",   \n    name = \"% Underserved Tracts\"\n  ) +\n  new_scale_fill()+\n  geom_sf(\n    data = hospitals, \n    aes(fill=type),      \n    size = 3, \n    shape = 21, \n    color = \"#FF8600\",     \n    stroke = 0.8\n  ) +\n  scale_fill_manual(\n    values = c(\"Hospital\" = \"#FF8600\"),\n    name = NULL\n  )+\n  labs(\n    title = \"Underserved Tracts per Counties in Pennsylvania\",\n    subtitle = str_wrap(\"Where an underserved tract is one where the center is at least 15 miles from the nearest hospital\",50),\n    caption =\"Data Sources: US Census Data, OpenDataPhilly\"\n  ) +\n  annotation_north_arrow(             \n    location = \"tr\",                  \n    which_north = \"true\",\n    style = north_arrow_minimal\n  ) +\n  theme_void() +\n  theme(\n    legend.position = \"right\",\n    legend.direction = \"vertical\",\n    plot.title = element_text(hjust = 0.5, size = 16, face = \"bold\"),\n    plot.subtitle = element_text(hjust = 0.5, size = 12),\n    plot.caption = element_text(hjust = 0.5, size = 9, margin = margin(t = 10))\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_kk_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\nvulnerable_tracts <- vulnerable_tracts %>%\n  st_as_sf() %>% \n  st_transform(st_crs(census_tracts))\n\nunderserved_tracts <- vulnerable_tracts[vulnerable_tracts$underserved==\"Underserved\",]\n\npa_counties$legend <- \"County Boundary\"\n\nggplot(census_tracts) +\n  geom_sf(\n    color=\"darkgrey\",\n    size=.5\n  )+\n  geom_sf(\n    data=underserved_tracts,\n    aes(fill = underserved)\n  )+\n  geom_sf(\n    data=pa_counties,\n    aes(color=legend),     \n    linewidth = .8,\n    fill=NA\n  )+\n  geom_sf(\n    data=hospitals,\n    aes(fill = type),      \n    size = 1, \n    shape = 21, \n    color = \"#FF8600\",     \n    stroke = 0.8\n  )+\n  scale_fill_manual(\n    values = c(\"Underserved\" = \"#485EFE\",\n               \"Hospital\" = \"#FF8600\"),\n    name = NULL  # or \"Legend\" if you want a title\n  ) +\n  scale_color_manual(\n    values = c(\"County Boundary\" = \"black\"),\n    name = NULL\n  ) +\n  annotation_north_arrow(             \n    location = \"tr\",                  \n    which_north = \"true\",\n    style = north_arrow_minimal\n  ) +\n  theme_void()+\n  labs(\n    title = \"Underserved Tracts in Pennsylvania\",\n    subtitle = str_wrap(\"Where an underserved tract's center is at least 15 miles from the nearest hospital\",50),\n    caption =\"Data Sources: US Census Data, OpenDataPhilly\"\n  ) +\n  theme(\n    legend.position = \"bottom\",\n    legend.direction = \"horizontal\",\n    plot.title = element_text(hjust = 0.5, size = 16, face = \"bold\"),\n    plot.subtitle = element_text(hjust = 0.5, size = 12),\n    plot.caption = element_text(hjust = 0.5, size = 9, margin = margin(t = 10))\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_kk_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n\ndep_regions<- st_read(\"data/DEPRegions2024_03.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `DEPRegions2024_03' from data source \n  `C:\\Users\\knoxk\\OneDrive\\Documents\\musa-5080\\portfolio-setup-kkxix\\labs\\lab2\\data\\DEPRegions2024_03.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 6 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -8963379 ymin: 4825316 xmax: -8314404 ymax: 5201420\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\ndep_regions <- dep_regions %>% st_transform(st_crs(vulnerable_tracts))\n\nvulnerable_tracts <- vulnerable_tracts %>% \n  mutate(\n      urban_rural = case_when(\n      total_popE >= 5000 ~ \"Urban\",\n      TRUE ~ \"Rural\"\n      )\n  )\n\nvulnerable_tracts_with_regions <- vulnerable_tracts %>%\n  st_join(dep_regions) %>%\n  st_drop_geometry()\n\nvulnerable_tracts_with_regions <- vulnerable_tracts_with_regions %>%\n  mutate(\n    Region = case_when(\n      SNAME == \"NCRO\"~\"North Central\",\n      SNAME ==\"NERO\"~\"North East\",\n      SNAME==\"NWRO\"~\"North West\",\n      SNAME==\"SCRO\"~\"South Central\",\n      SNAME==\"SERO\"~\"South East\",\n      SNAME==\"SWRO\"~\"South West\"\n    )\n  )\n  \n  \nggplot(vulnerable_tracts_with_regions)+\n  geom_boxplot(\n    aes(x=Region, y=distance_to_nearst_hospital)\n  )+\n  labs(\n    title=\"Distance of Vulnerable Tracts to Nearest Hospital by Region\",\n    caption=str_wrap(\"Where a vulnerable tract is in the top 25% of concentration of elderly population or 215% of the Federal Poverty Line for 2-person household. Data sources: US Census, Pennsylvania Spatial Data Access  -- Department of Environmental Protection Regions\",100),\n    y=str_wrap(\"Distance from Center of Tract to Nearest Hospital\",50),\n    x=\"Region of Tract\"\n  )+\n  theme(\n    legend.position = \"bottom\",\n    legend.direction = \"horizontal\",\n    plot.title = element_text(hjust = 0.5, size = 16, face = \"bold\"),\n    plot.subtitle = element_text(hjust = 0.5, size = 12),\n    plot.caption = element_text(hjust = 0.5, size = 9, margin = margin(t = 10))\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_kk_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\nNorthern Pennsylvania vulnerable populations generally are location farther from hospitals than Southern Pennsylvania, with North Central PA having the highest median and upper quartiles of distance to the nearest hospital of all 6 regions. However another trend we can see is that the highest number of outliers fall within the South East and South West regions, home to the two biggest cities in PA, Philadelphia and Pittsburgh, respectively. That shows that these regions have more tracts that are facing very different needs that the middle 50% of the region.\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n\n---\n\n\n### Your Analysis\n\n#### Digital Justice\n\n**Option C: Digital Equity** \n\n- **Data:** Census Broadband access, device access, and income, Philadelphia free wifi spots from OpenDataPhilly\n- **Question:** \"Do digitally disadvantaged neighborhoods have equitable access to city internet?\"\n- **Operations:** Buffer free wifi spots with a computer (10-minute walk = 0.5 mile), calculate connectivity by tract, determine digitally vulnerable tracts from census data and underserved tracts by distance from buffers. \n- **Policy relevance:** Digital equity, broadband infrastructure, internet-connected device access\n\n1. **Find and load additional data**\n\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\nv21 <- load_variables(2023, \"acs5\", cache = TRUE)\n\n# Search for broadband and computer-related variables\nbb_vars <- v21 %>% filter(str_detect(label, \"broadband\"))\ncomp_vars <-v21 %>% filter(str_detect(label, \"computer\"))\n\n#B28003_002 = total with computer\n#B28002_004 = total with broadband internet subscription\n\nphilly_digital_access <-  get_acs(\n  geography = \"tract\",\n  variables = c(\n    total_pop = \"B01003_001\",\n    has_computer = \"B28003_002\", \n    has_broadband = \"B28002_004\"\n  ),\n  state = \"PA\",\n  county = \"Philadelphia\",\n  year = 2023,\n  output = \"wide\"\n)\n\nfree_wifi_spots <- st_read(\"data/free_city_wifi_locations.shp\")%>%st_transform(2272)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `free_city_wifi_locations' from data source \n  `C:\\Users\\knoxk\\OneDrive\\Documents\\musa-5080\\portfolio-setup-kkxix\\labs\\lab2\\data\\free_city_wifi_locations.shp' \n  using driver `ESRI Shapefile'\nreplacing null geometries with empty geometries\nSimple feature collection with 254 features and 47 fields (with 1 geometry empty)\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -8378350 ymin: 4852065 xmax: -8345555 ymax: 4883809\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nphilly_digital_access <- left_join(\n  philly_digital_access,\n  census_tracts,\n  by=\"GEOID\"\n) %>%\n  st_as_sf() %>%\n  st_transform(2272)\n\nggplot(philly_digital_access)+\n  geom_sf()+\n  geom_sf(\n    data=free_wifi_spots\n  )+\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_kk_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n**Questions to answer:**\n\n- What dataset did you choose and why?\n  - I choose the ACS variables showing whether a household has broadband access and whether they have a computer, as well as OpenDataPhilly's database of free wi-fi locations, which inlcudes a variable showing how many public use computers are available at the location. \n- What is the data source and date?\n  - The ACS data is 5-year data from 2018 - 2023, and the wi-fi locations are from 2024, so the home broadband and computer access data may be slightly outdated. Also important to note is 2018 - 2023 range includes the pandemic, a period in which there was unprecedented investment in home internet subsidies that have expired in 2024 ![Affordable Connectivity Program](https://technical.ly/civic-news/affordable-connectivity-program-ending-comcast-verizon-congress-act/).\n- How many features does it contain?\n  - There are 254 free-wifi locations, and 408 census tracts in Philadelphia. \n- What CRS is it in? Did you need to transform it?\n  - Before transformation, both datasets were in web mercator, EPSG 3857, and since Philly falls within southern pennsylvania, I transformed it to Pennsylvania South state plane projection, EPSG 2272. \n---\n\n2. **Pose a research question**\n\nDo digitally vulnerable tracts have adequate access to free wifi spots with computers?\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n\n#Filter Philly census tracts by the most digitally vulnerable: in the top quartile of percent of tract that has no home broadband or top quartile of percent of tract with no computer. \nphilly_digital_access <- philly_digital_access %>%\n  mutate(\n    percent_no_bb = (1-has_broadbandE/total_popE.x)*100,\n    percent_no_comp = (1-has_computerE/total_popE.x)*100\n  )\n\nsummary(philly_digital_access$percent_no_bb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  25.95   56.43   62.88   61.71   68.65  100.00      17 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(philly_digital_access$percent_no_comp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  25.20   54.34   60.27   59.29   65.62  100.00      17 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#based on summary stats, the most digitally vulnerable are tract with 68.65% or more of households that do not have home broadband or 65.62% or more of households that do not have a computer. \n\ndigit_vulnerable_philly <- philly_digital_access %>%\n  filter(percent_no_bb>=68.65 | percent_no_comp>=65.62 )\n\n#visually examine digitally vulnerable tracts and free wifi spots with computers\nggplot(philly_digital_access)+\n  geom_sf()+\n  geom_sf(\n    data=digit_vulnerable_philly,\n    fill=\"purple\"\n  )+\n  geom_sf(data=free_wifi_spots[free_wifi_spots$computers_==\"Y\",])+\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_kk_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find nearest free wifi spots with a computer to tract centroids \ndigit_vulnerable_centroids <- st_centroid(digit_vulnerable_philly)\nnearest_wifi_spot_comp <- st_nearest_feature(digit_vulnerable_centroids, free_wifi_spots[free_wifi_spots$computers_==\"Y\",])\n\ndigit_vulnerable_philly <- digit_vulnerable_philly %>%\n  mutate(nearest_wifi_spot_geom = free_wifi_spots$geometry[nearest_wifi_spot_comp])\n\ndigit_vulnerable_philly <- digit_vulnerable_philly %>%\n  mutate(distance_wifi_spot_comp = set_units(st_distance(digit_vulnerable_centroids, digit_vulnerable_philly$nearest_wifi_spot_geom, by_element = TRUE), \"mi\"))\n\nsummary(digit_vulnerable_philly$distance_wifi_spot_comp) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.3979  3.3372  5.8429  6.0722  7.9510 13.7746 \n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Find walking distance buffers around free wifi spots with computers \nfree_wifi_buffers <- free_wifi_spots %>%\n  filter(computers_==\"Y\" & to_display==\"ACTIVE\")%>%\n  st_buffer(dist = 2640)  # 2640 ft = .5 mi\n\n\n#dissolve overlapping buffers \nfree_wifi_buffers_dissolve <- free_wifi_buffers%>%\n  st_union() %>%\n  st_cast(\"POLYGON\")%>%\n  st_as_sf()%>%\n    mutate(\n    legend= \".5 mi from Free Wifi Spot w Computer\"\n  )\n\n  \n#examine buffers and tracts overlap\nggplot(philly_digital_access)+\n  geom_sf(\n    color=\"darkgray\",\n    linewidth=.5,\n    alpha=.5\n  )+\n  geom_sf(\n    data=digit_vulnerable_philly,\n    aes(fill=percent_no_bb+percent_no_comp)\n  )+\n  scale_fill_gradient(\n    low=\"#FFCF33\",\n    high=\"#F53D00\",\n    name=\"% No broadband + % No Computer\"\n  )+\n  new_scale_fill()+\n  geom_sf( \n    data=free_wifi_buffers_dissolve,\n    aes(fill=legend),\n    color=\"black\",\n    linewidth=.8,\n    alpha=0.4\n  )+\n  scale_color_manual(\n    values = c(\".5 mi from Free Wifi Spot w Computer\" =  \"#F5A6E6\") ,\n    name=NULL\n  )+\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_kk_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Define underserved tract as a tract that is digitally vulnerable and outside walking distance to a free wifi spot with a computer. \n\noverlap <- st_intersects(digit_vulnerable_philly, free_wifi_buffers)\n\nno_overlap <- lengths(overlap) == 0\n\ndigit_underserved <- digit_vulnerable_philly[no_overlap, ]\n\nsummary(digit_underserved)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    GEOID               NAME            total_popE.x   total_popM.x   \n Length:30          Length:30          Min.   :1027   Min.   :  82.0  \n Class :character   Class :character   1st Qu.:3868   1st Qu.: 624.0  \n Mode  :character   Mode  :character   Median :4604   Median : 808.0  \n                                       Mean   :4793   Mean   : 927.2  \n                                       3rd Qu.:6202   3rd Qu.:1139.5  \n                                       Max.   :8145   Max.   :2091.0  \n                                                                      \n has_computerE  has_computerM   has_broadbandE has_broadbandM \n Min.   :   0   Min.   : 11.0   Min.   :   0   Min.   : 11.0  \n 1st Qu.:1121   1st Qu.:155.8   1st Qu.:1103   1st Qu.:165.0  \n Median :1515   Median :226.0   Median :1328   Median :229.0  \n Mean   :1444   Mean   :223.7   Mean   :1346   Mean   :227.7  \n 3rd Qu.:1785   3rd Qu.:291.0   3rd Qu.:1677   3rd Qu.:284.0  \n Max.   :2528   Max.   :431.0   Max.   :2247   Max.   :444.0  \n                                                              \n   STATEFP            COUNTYFP           TRACTCE            GEOIDFQ         \n Length:30          Length:30          Length:30          Length:30         \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    NAME.x            NAMELSAD            STUSPS           NAMELSADCO       \n Length:30          Length:30          Length:30          Length:30         \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  STATE_NAME            LSAD               ALAND             AWATER       \n Length:30          Length:30          Min.   : 184674   Min.   :      0  \n Class :character   Class :character   1st Qu.: 491366   1st Qu.:      0  \n Mode  :character   Mode  :character   Median : 613069   Median :      0  \n                                       Mean   : 863564   Mean   :  46550  \n                                       3rd Qu.: 854698   3rd Qu.:      0  \n                                       Max.   :4488319   Max.   :1362058  \n                                                                          \n    NAME.y          median_incomeE   median_incomeM   total_popE.y \n Length:30          Min.   : 13721   Min.   : 2945   Min.   :1027  \n Class :character   1st Qu.: 38976   1st Qu.:11549   1st Qu.:3868  \n Mode  :character   Median : 54871   Median :14980   Median :4604  \n                    Mean   : 54849   Mean   :17043   Mean   :4793  \n                    3rd Qu.: 62857   3rd Qu.:22100   3rd Qu.:6202  \n                    Max.   :101094   Max.   :43870   Max.   :8145  \n                    NA's   :1        NA's   :1                     \n  total_popM.y       over_65E         over_65M               geometry \n Min.   :  82.0   Min.   :  0.00   Min.   :  3.00   MULTIPOLYGON :30  \n 1st Qu.: 624.0   1st Qu.:  6.00   1st Qu.: 13.00   epsg:2272    : 0  \n Median : 808.0   Median : 23.00   Median : 28.50   +proj=lcc ...: 0  \n Mean   : 927.2   Mean   : 31.63   Mean   : 36.50                     \n 3rd Qu.:1139.5   3rd Qu.: 50.50   3rd Qu.: 50.75                     \n Max.   :2091.0   Max.   :123.00   Max.   :121.00                     \n                                                                      \n percent_no_bb    percent_no_comp    nearest_wifi_spot_geom\n Min.   : 67.08   Min.   : 63.23   POINT        :30        \n 1st Qu.: 69.48   1st Qu.: 66.97   epsg:2272    : 0        \n Median : 70.93   Median : 68.08   +proj=lcc ...: 0        \n Mean   : 72.34   Mean   : 70.55                           \n 3rd Qu.: 73.19   3rd Qu.: 71.73                           \n Max.   :100.00   Max.   :100.00                           \n                                                           \n distance_wifi_spot_comp\n Min.   : 2.465         \n 1st Qu.: 5.471         \n Median : 6.020         \n Mean   : 7.138         \n 3rd Qu.: 9.588         \n Max.   :13.775         \n                        \n```\n\n\n:::\n\n```{.r .cell-code}\n#what are characteristics of top 10 digitally underserved tracts by absolute number of those with no broadband + those with no computer? \n\n#note, the sum of estiamated households without computer and without broadband is not an accurate estimate of reality because those without one are likely overlapping with the other. This metric is just being used to create a metric showing reflecting broadband and computer need in one. \ndigit_underserved<-digit_underserved%>%\n  mutate(\n    digit_need_heuristic = (total_popE.x - has_computerE)+(total_popE.x - has_broadbandE)\n  )\n\ntop_10_digit_underserved <- digit_underserved%>%\n  arrange(desc(digit_need_heuristic))%>%\n  slice_head(n = 10)\n \ntop_10_digit_underserved %>%\n  st_drop_geometry()%>%\n  select(c(\n    \"percent_no_bb\",\n    \"percent_no_comp\",\n    \"median_incomeE\",\n    \"distance_wifi_spot_comp\"\n  )) %>%\n  kable(\n    col.names = c(\"Percent w/o Broadband\",\n                  \"Percent w/o a Computer\", \n                  \"Median Income\", \n                  \"Distance to Free Wi-Fi spot w/ Computer\"),\n    digits = 1,\n    format.args = list(big.mark = \",\"),\n    align = \"l\",\n    caption = \"10 Census Tracts in Philadelphia that are most Digitally Vulnerable and Distance to Nearest Free Wi-Fi Spot with a Public Computer\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: 10 Census Tracts in Philadelphia that are most Digitally Vulnerable and Distance to Nearest Free Wi-Fi Spot with a Public Computer\n\n|Percent w/o Broadband |Percent w/o a Computer |Median Income |Distance to Free Wi-Fi spot w/ Computer |\n|:---------------------|:----------------------|:-------------|:---------------------------------------|\n|82.4                  |79.6                   |38,976        |2.464926 [mi]                           |\n|73.3                  |70.4                   |13,721        |7.369100 [mi]                           |\n|75.5                  |71.6                   |56,818        |10.021851 [mi]                          |\n|73.6                  |71.7                   |68,652        |9.960189 [mi]                           |\n|70.9                  |67.3                   |33,419        |5.459912 [mi]                           |\n|76.1                  |74.2                   |50,245        |5.314348 [mi]                           |\n|69.9                  |67.5                   |100,857       |13.774589 [mi]                          |\n|67.8                  |67.5                   |71,551        |3.367629 [mi]                           |\n|67.6                  |67.1                   |54,871        |8.256588 [mi]                           |\n|68.1                  |66.5                   |93,300        |12.009875 [mi]                          |\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Map the underserved tracts and wifi spots buffers \ndigit_underserved<-digit_underserved%>%\n  mutate(\n    legend=\"Digitally Underserved Tract\"\n  )\n\nggplot(philly_digital_access)+\n  geom_sf(\n    color=\"darkgray\",\n    linewidth=.5,\n    alpha=.5\n  )+\n  geom_sf(\n    data=digit_underserved,\n    aes(fill=\"Digitally Underserved Tract\")\n  )+\n  scale_fill_manual(\n    values = c(\"Digitally Underserved Tract\" = \"#3F88C5\"),\n    name=NULL\n  )+\n  new_scale_fill()+\n  geom_sf( \n    data=free_wifi_buffers_dissolve,\n    aes(fill=\".5 mi from Free Wifi Spot w Computer\"),\n    color=\"black\",\n    linewidth=.8,\n    alpha=0.4\n  )+\n  scale_color_manual(\n    values = c(\".5 mi from Free Wifi Spot w Computer\" =  \"#F5A6E6\") \n  )+\n  guides(fill = guide_legend(title = NULL))+\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_kk_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\n[Write your findings here]\n\n\n## Finally - A few comments about your incorporation of feedback!\nTake a few moments to clean up your markdown document and then write a line or two or three about how you may have incorporated feedback that you recieved after your first assignment. \n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n\n**File naming:** `LastName_FirstName_Assignment2.html` and `LastName_FirstName_Assignment2.qmd`\n\n---\n\n",
    "supporting": [
      "assignment2_kk_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}